### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by janjongboom** [bit/subprocess#5]
Hi, couldn't find an email address in your profile, but thanks a lot for this module. Was just what I need.

**Comment by bit** [comment]
Great to hear. What do you use it for?

**Comment by janjongboom** [comment]
Needed something similar to the node.js `child_process` module, but accessible from user code for our embedded platform that runs Gecko. Similar to what I wrote up here: http://ee.telenor.io/gonzo/firefox/2014/12/17/new-apis.html
